### ISSUE TITLE
Action Route: Order Item from Wishlist

### ISSUE THREAD

**Issue by hfstarman** [Wishlist-Squad/wishlists#62]
**As a** User
**I need** purchase items directly from my wishlists
**So that** I may more conveniently give this company more money

**Assumptions:**
* Create flag in Prouduct stating that the customer ordered this item
* Create new route to `wishlists/{id}/item/{item_id}/purchase` for directly purchasing the item

**Acceptance Criteria:**
```gherkin
When I target `wishlists/{id}/item/{item_id}/purchase`
Then I should see that the purchased flag is set in the product
```

**Comment by SheraLee** [comment]
There is a Shopcarts group. I am thinking should we just add the product that the customer what to purchase into his shop cart.

**Comment by hfstarman** [comment]
Sure that makes sense

**Comment by hfstarman** [comment]
Sure that makes sense

**Comment by SheraLee** [comment]
I am confused. For purchase, should there be a button at the front end that should call our get and shop chart's creat?

**Comment by hfstarman** [comment]
yeah if there were a front end then there would be a button by the item in the wishlist that would add the item to the cart
